language: ruby
rvm:
- 2.3.4
services:
- postgresql
before_script:
- bundle pack
- sh -e /etc/init.d/xvfb start
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:setup
- export PARALLEL_TEST_PROCESSORS=4