language: ruby
rvm:
- 2.4.0
services:
- postgresql
before_script:
- bundle pack
- sh -e /etc/init.d/xvfb start
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:setup
- export PARALLEL_TEST_PROCESSORS=4
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: EJiQXp35HN7PYkxI9FSpYawcUxSRS7liaZVpaIYB/5TpCK2srVkuQlBESUWM2gECv2YgMEYvJF2b4CXJJxll+1vVrkm9AgGhbSUQ/0YYlwvOWQVbEw1nzamm/tUwUyqwwd9mtb0tnH74iqaGVx+EkDIlbwiehl09IDOnikacrJ4apf8PYnpkT2N4unES3hd/exbxe4Lgw2otypTagKyvjDDAR4LVzq9Q/OI2wypah10fhNhdCMEOPC/4syHB/1O5/BQ3RPRIOkvS1MxLf8M4PNUbaeqZIB6B2lB769I7jWdDdlcHVRmjrwOo8goAryHyk8+9oVLLh+HBR+3lV7P0SLuk+MKQn0eUD3cFy8IUl+6unFysgVHvMlG0uEaVOzHDBpqEnSHRSYW88TAkjxx5TuCNl4yXA8JZ7+xYqOad8UBOKdXhPKGv1jrjj6lZJWHBCj6qf6YGux3OFIW5p27E2gYg+XirCCJCpxTsGhUyP1ZCtqYQjXiWNPPWmd2GxEJO75u3RWiC62BZl50v7Y03yT1+8DqVrewXagtFf92mbqVPHTHqEBFDaO05BBzutpOV4grT1XvqY+TY7XBhA3lYkoDYedwurcL94qKRgxAQFDkHUqi7CFENxjW9rxA1AWRNvf3bQyCIrRa9uvCUR4JhEyhDYv3SB0brvFsYGUozeXM=
  app: dodi-app
  on:
    repo: fybwid/dodi
