language: ruby
rvm:
- 2.4.0
services:
- postgresql
before_install: gem install bundler
before_script:
- sh -e /etc/init.d/xvfb start
- psql -c "CREATE DATABASE dodi_production;" -U postgres
- psql -c "CREATE DATABASE dodi_test;" -U postgres
- psql -c "CREATE DATABASE dodi_development;" -U postgres
- cp config/database.travis.yml config/database.yml
- export PARALLEL_TEST_PROCESSORS=4
- RAILS_ENV=development bundle exec rake db:create db:migrate
deploy:
  provider: heroku
  api_key:
    secure: QOe0/ChJRCQNhdOxIvrPe0fiD1EJDNSn7dCIU0eNw12UvqJPLTjndWSw6ydqtPKHurcPsp1ik5k4R2O2tEgztWjeCKTIf5PCH9cq9i7IVANn2XOlWE4naLYk9dYy5vrgySm9lEoggMKhBM60Fi4387MuFFdqrEUh/7ZtN6bK4RlaguudTwqBEwvY48mQ36cp2s01sN6lHGriOwSRBxPbHmy3PJ3N0JUwnbtsENJ0Cgt7bf3aMWjSbgxcrsMlTPUESmSi3mOvEbPwFE1YPLMgEkbut6OynxjpaEeOweDw3jbtJ25qAngL8Z0KgibJW/LqLczOlEpb/iEjM0vOQb6zYLlqaIBlVOpu18aBcMlOGabS/4yCX/W91ib1OAaDzS0/3oC+VjKfd2sx7CnCLIP8aQWLfx5uuQhH20gfkmRP4txHf8EU1ODq6NHzzvclcBt/Z9vhBPMuyANKdZ8ff0M8oDcVcxQZkSF2zLbM5J85pM8tDfjqObLQe6Wk1AsNv6mvfzHwfFG7uhaxub+4r4mu38IwKBl6ROw0IleoSfEezU9QYbyYLN1XGsKkiGXhOsP2eBXKApa4a/dfDAOXM/QWTAWJlsaXz5XvB/8EdyW6F17lzidDR31RW96i6419BJGy0WPmU2sNTUICuisqwnM7ABPIbQWfC6zoeT1fLtc5AhM=
  app: dodi
  on:
    repo: fybwid/dodi
