language: ruby
rvm:
- 2.4.0
services:
  - postgresql
  
before_install: gem install bundler

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - psql -c "CREATE DATABASE dodi_production;" -U postgres
  - psql -c "CREATE DATABASE dodi_test;" -U postgres
  - psql -c "CREATE DATABASE dodi_development;" -U postgres
  - cp config/database.travis.yml config/database.yml
  - export PARALLEL_TEST_PROCESSORS=4
  - RAILS_ENV=development bundle exec rake db:create db:migrate

deploy:
  provider: heroku
  api_key:
    secure: "FR2HUa9Lj8QnFi5rZUAsr0bwVgjF+ztGCasOSGALqwz7qSBGhhRKEeq4xXiII2OJkCyAlVDGfa5udlBpN+coXvNXRKI/V36NSRQB7qiqE+lWnqPP2El+gFAZuE1uJYFX2dNFckSWoSNesil6Nqh4E74kSx/H/BaAcH5FA1bh70uZs6w8J+7sQeLGIgjnmCTN247IeXwv3UA5JZuyMTpVlnLlAb+tKRALgCcUg1oZYBRDRyvfb+Za1wKFVsTorMwMgjXWkvXZE4olXzVjaUl4VtXqLBLCGXQRkYkoMy4O3bgcjQcKfc+yh2libxTz7MSFnOpr7FwZ9SdJ+ojh4mAU9TatK1uvJpiVOikIjIRfY8X9P9V/fGX0y+lxHC7HH3z0z7FBazO5YOf2jMrjgpNXM84wkzjfvm54tWEU17Sr3YZeRdRrMAo/Lf84+yqkCIcM1Yp2E7znS+0wxhkYTUOWqZqgvvR7dYeIsTeczoPBaj4TmroRQzeXTXiIO0bnyMzFsc7haMlwW+oMzLJGineIaqLIFHEnGwPmHQfymE4NOfsQJplJmsZ8CBw3y2tzh1hqZLflxKPNLqZdt5VRzVtmSvNc6NTrwuSuMRWW+af/L1Nwiwqln0QLMfnqAFcW9u72JPXxxxGoYxWlJJ7TNCnQOxiXVz+P6rksyPHi0SIs4VI="
  app: dodi-app
  on:
    repo: fybwid/dodi